title: Food Blender
description: Choose fruit and vegetables and blend them into a colorful mix

baseurl: /food-blender-site
github_repo: MichaelCurrin/food-blender-site

exclude:
  - LICENSE
  - README.md
  - Makefile
